<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saikats-MBP.fios-router.home" name="com.selenium.facebook.pom.testcases.LoginTest" tests="5" failures="1" timestamp="7 Aug 2017 01:40:51 GMT" time="12.000" errors="0">
  <testcase name="test_profile" time="1.899" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_4" time="0.196" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_1" time="1.735" classname="com.selenium.facebook.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Test Something 1 has been failed">
      <![CDATA[java.lang.AssertionError: Test Something 1 has been failed
	at org.testng.Assert.fail(Assert.java:94)
	at com.selenium.facebook.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:75)
	at com.selenium.facebook.pom.testcases.LoginTest.test_1(LoginTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- test_1 -->
  <testcase name="test_2" time="0.181" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_Login" time="7.989" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
</testsuite> <!-- com.selenium.facebook.pom.testcases.LoginTest -->
