<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Saikats-MBP.fios-router.home" name="Login Test" tests="5" failures="1" timestamp="12 Aug 2017 20:50:27 GMT" time="12.265" errors="0">
  <testcase name="test_Login" time="7.953" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_profile" time="2.109" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_4" time="0.002" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_2" time="0.007" classname="com.selenium.facebook.pom.testcases.LoginTest"/>
  <testcase name="test_1" time="1.302" classname="com.selenium.facebook.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Test Something 1 has been failed">
      <![CDATA[java.lang.AssertionError: Test Something 1 has been failed
	at com.selenium.facebook.pom.testcases.base.BaseTest.reportFailure(BaseTest.java:75)
	at com.selenium.facebook.pom.testcases.LoginTest.test_1(LoginTest.java:64)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test_1 -->
</testsuite> <!-- Login Test -->
